export API_KEY=iK_3SPA-1B7YiXuDXmoTgJug-pvaXtRVm72OZIz6bWWMr2O-4YbZtgzqzWA0pAtwWtMZxpN07nkNlaeretAwS_nzaVrWuDRKjDh0sG1yHBLA2BZ4GwIAGqL9PZ5bW3Yx
export DJANGO_SECRET_KEY=jslkjflsajfslafjlsjkhsfkjhsafhsufhsiuhfias
