# Generated by Django 2.0.7 on 2018-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20180802_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='US', max_length=20),
            preserve_default=False,
        ),
    ]
