# Generated by Django 2.0.7 on 2018-08-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20180804_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.AddField(
            model_name='canteenuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='lunch.Company'),
        ),
        migrations.RemoveField(
            model_name='canteenuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='canteenuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_canteenuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
