# Generated by Django 2.0.7 on 2018-08-04 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_auto_20180804_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_canteenuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
