# Generated by Django 2.0.7 on 2018-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0008_auto_20180804_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='restaurantId',
            field=models.CharField(default='1234', max_length=22),
            preserve_default=False,
        ),
    ]
