# Generated by Django 2.0.7 on 2018-08-05 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0009_event_restaurantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteenuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='canteenuser',
            name='colleagues',
            field=models.ManyToManyField(blank=True, related_name='_canteenuser_colleagues_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
