# Generated by Django 2.0.7 on 2018-08-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_auto_20180805_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='restaurantName',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
    ]
